# Generated by Django 4.2.11 on 2024-04-18 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gpio_id', models.IntegerField()),
                ('size', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('packets_id', models.IntegerField()),
                ('reserved', models.BooleanField()),
                ('status', models.BooleanField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.box')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='rig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rig'),
        ),
    ]
