# Generated by Django 4.2.11 on 2024-04-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rig',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
