# Generated by Django 4.2.11 on 2024-04-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_rig_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='packet',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
