# Generated by Django 4.2.11 on 2024-04-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_packet_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Packet',
            new_name='Package',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='packets_id',
            new_name='package_id',
        ),
    ]
