# Generated by Django 4.2.11 on 2024-04-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_packet_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='bar_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
