# Generated by Django 4.2.11 on 2024-04-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_package_bar_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='reserved',
        ),
        migrations.AddField(
            model_name='box',
            name='reserved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
