# Generated by Django 4.2.11 on 2024-05-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_box_rig'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='user_bar_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
